[package]
name = "ts-similarity-core"
version = "0.1.0"
edition = "2021"

[dependencies]
oxc_parser = { workspace = true }
oxc_ast = { workspace = true }
oxc_span = { workspace = true }
oxc_allocator = { workspace = true }
regex = "1.10"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "tsed_benchmark"
harness = false

[[bench]]
name = "function_comparison"
harness = false